### ISSUE TITLE
Numbers of generated images

### ISSUE THREAD

**Issue by Jumponthemoon** [yasserben/CLOUDS#3]
Hi there,

Shout out to your great work!

I'm wondering how many generated images you used for training? I saw there are 100 prompts in the provided txt file, does it mean the model trained with 100 generated images?

**Comment by yasserben** [comment]
Hi ! Thank you, I appreciate it.

Indeed, we have 100 prompts but our model was trained on 5000 images, so we generate 50 different images for each prompt. I hope that helps! If anything's still unclear, just let me know.

**Comment by Jumponthemoon** [comment]
Brilliant! Thanks for your reply and it answered my question.
