### ISSUE TITLE
请问训练该模型需要什么样的显卡？

### ISSUE THREAD

**Issue by liuzywen** [yasserben/CLOUDS#5]

**Comment by yasserben** [comment]
You can train CLOUDS on a Nvidia V100 32GB

**Comment by liuzywen** [comment]
3090（24GB）可以训练得起来吗？

**Comment by yasserben** [comment]
I think you can make it run on a 3090 (24GB), especially if you change the backbone to a ResNet-101 or ResNet-50 for sure

**Comment by liuzywen** [comment]
Thanks very much.
