### ISSUE TITLE
Tutorial on how to use the demo script

### ISSUE THREAD

**Issue by AndreiBaraian** [yasserben/CLOUDS#6]
Hi! First of all, thanks for the great repository! Are there any detailed instructions on how to use the demo.py and run it on a set of custom images? I have tried using it, but I keep getting into various errors. I had to remove the wandb param from the config file of clouds_config.yaml, as I was getting KeyError: 'WANDB'. Then, I stumbled on 'FileNotFoundError: [Errno 2] No such file or directory: 'clouds/data/datasets/lvis_1203_with_prompt_eng.txt''. 

I have run it with the following command: python demo.py --config-file configs/segmentation/clouds_config.yaml --input ../da_datasets/uavid_v1.5_official_release_image/uavid_test/seq22/Images/*.png

Thanks and appreciate it!

**Comment by yasserben** [comment]
Hi,

Thanks for your message !

The files `demo.py` and `predictor.py` are part of the original repository, and I haven’t modified them to ensure compatibility in this context. Here’s what I recommend:

1. **Modify the Existing Files**:  
   Adapt these files to suit your use case. For example, you can address the error you had by adjusting the path to `clouds/data/datasets/classes_prompt_eng.txt`, which corresponds to the standard 19 classes typically used for urban driving scenes.

2. **Use a Custom Dataset**:  
   If you plan to test CLOUDS on a large number of images, it’s more efficient to create a custom dataset class. You can follow the [Detectron2 dataset tutorial](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html) to set up your dataset, similar to how it has been done in the repository for datasets like GTA5, Cityscapes, Mapillary, and BDD.

   Once your custom dataset is ready, you can run the evaluation using the following command:
   ```bash
   python train_net.py --eval-only --config-file /path/to/config_file \
   MODEL.WEIGHTS /path/to/checkpoint_file
Ensure that the YAML configuration file points to your newly added dataset.

Let me know if you need further clarification or assistance!
